labels: ["Q&A"]
body:
  - type: markdown
    attributes:
      value: |
        ❓ **提问时间！**
        
        有问题？社区来帮助您！这里是提问和分享解决方案的地方。

  - type: textarea
    id: question
    attributes:
      label: ❓ 您的问题
      description: 请详细描述您的问题
      placeholder: 我遇到了...，应该如何解决？
    validations:
      required: true

  - type: dropdown
    id: difficulty
    attributes:
      label: 🎯 问题难度
      description: 您认为这个问题的难度如何？
      options:
        - 初学者问题
        - 中级问题
        - 高级问题
        - 专家级问题
      default: 0

  - type: textarea
    id: context
    attributes:
      label: 📖 背景信息
      description: 提供一些背景信息帮助大家更好地理解
      placeholder: 我的使用场景是...

  - type: textarea
    id: tried
    attributes:
      label: 🔍 已尝试的方法
      description: 您已经尝试了什么？
      placeholder: |
        我已经尝试了：
        1. 查看文档...
        2. 搜索相关问题...
        3. 尝试了...

  - type: textarea
    id: environment
    attributes:
      label: 🖥️ 环境信息
      description: 请提供相关的环境信息
      value: |
        - 操作系统: 
        - Shortlinker 版本: 
        - 部署方式: 
        - 其他相关信息: