/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/v1/analytics/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/v1/analytics/devices - 获取设备分析 */
        get: operations["get_device_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/analytics/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/v1/analytics/export - 导出报告（流式响应） */
        get: operations["export_analytics_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/analytics/geo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/v1/analytics/geo - 获取地理位置分布 */
        get: operations["get_geo_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/analytics/referrers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/v1/analytics/referrers - 获取来源统计 */
        get: operations["get_referrer_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/analytics/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/v1/analytics/top - 获取热门链接 */
        get: operations["get_top_links"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/analytics/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/v1/analytics/trends - 获取点击趋势 */
        get: operations["get_analytics_trends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登录验证 - 检查管理员 token */
        post: operations["admin_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出 - 清除 cookies */
        post: operations["admin_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新 token */
        post: operations["refresh_admin_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 验证 token - 如果中间件通过，则 token 有效 */
        get: operations["verify_admin_token"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有配置 */
        get: operations["list_configs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/config/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重新加载配置 */
        post: operations["reload_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/config/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有配置的 schema */
        get: operations["get_config_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/config/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取单个配置 */
        get: operations["get_config"];
        /** 更新配置 */
        put: operations["update_config"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/config/{key}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 执行配置 action（如生成 token）
         * @description POST /admin/v1/config/{key}/action
         */
        post: operations["execute_config_action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/config/{key}/execute-and-save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 执行配置 action 并保存（安全版本）
         * @description POST /admin/v1/config/{key}/execute-and-save
         */
        post: operations["execute_and_save_config_action"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/config/{key}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取配置变更历史 */
        get: operations["get_config_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有链接（支持分页和过滤） */
        get: operations["list_links"];
        put?: never;
        /** 创建新链接 */
        post: operations["create_link"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/links/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 批量更新链接 */
        put: operations["batch_update_links"];
        /** 批量创建链接 */
        post: operations["batch_create_links"];
        /** 批量删除链接 */
        delete: operations["batch_delete_links"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/links/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出链接为 CSV（流式响应） */
        get: operations["export_links"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/links/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 导入链接从 CSV */
        post: operations["import_links"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/links/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取单个链接 */
        get: operations["get_link"];
        /** 更新链接 */
        put: operations["update_link"];
        post?: never;
        /** 删除链接 */
        delete: operations["delete_link"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/links/{code}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/v1/links/{code}/analytics - 获取单链接详细统计 */
        get: operations["get_link_analytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/links/{code}/analytics/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /admin/v1/links/{code}/analytics/devices - 获取单链接设备分析 */
        get: operations["get_link_device_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取链接统计信息 */
        get: operations["get_link_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description 配置 Action 类型枚举
         *
         *     用于标识配置项可执行的操作（如生成 token）。
         *     这是一个与 ValueType 正交的概念 - 任何类型的配置都可以有可选的 action。
         * @enum {string}
         */
        ActionType: "generate_token";
        /** @description Analytics 查询参数 */
        AnalyticsQuery: {
            /** @description 结束日期 (ISO 8601) */
            end_date?: string | null;
            group_by?: null | components["schemas"]["GroupBy"];
            /**
             * Format: int32
             * @description 返回数量限制
             */
            limit?: number | null;
            /** @description 开始日期 (ISO 8601) */
            start_date?: string | null;
        };
        ApiResponse_AuthSuccessResponse: {
            /** Format: int32 */
            code: number;
            /** @description 认证成功响应 */
            data?: {
                /** Format: int64 */
                expires_in: number;
                message: string;
            };
            message: string;
        };
        ApiResponse_BatchResponse: {
            /** Format: int32 */
            code: number;
            data?: {
                failed: components["schemas"]["BatchFailedItem"][];
                success: string[];
            };
            message: string;
        };
        ApiResponse_ConfigActionResponse: {
            /** Format: int32 */
            code: number;
            /** @description 配置 action 执行响应 */
            data?: {
                value: string;
            };
            message: string;
        };
        ApiResponse_ConfigItemResponse: {
            /** Format: int32 */
            code: number;
            /** @description 配置项响应 */
            data?: {
                is_sensitive: boolean;
                key: string;
                requires_restart: boolean;
                updated_at: string;
                value: string;
                /** @description 值类型 */
                value_type: components["schemas"]["ValueType"];
            };
            message: string;
        };
        ApiResponse_ConfigUpdateResponse: {
            /** Format: int32 */
            code: number;
            /** @description 配置更新响应 */
            data?: {
                is_sensitive: boolean;
                key: string;
                message: string | null;
                requires_restart: boolean;
                value: string;
            };
            message: string;
        };
        ApiResponse_DeviceAnalyticsResponse: {
            /** Format: int32 */
            code: number;
            /** @description 设备分析响应 */
            data?: {
                /** Format: double */
                bot_percentage: number;
                browsers: components["schemas"]["CategoryStatsResponse"][];
                devices: components["schemas"]["CategoryStatsResponse"][];
                operating_systems: components["schemas"]["CategoryStatsResponse"][];
                /** Format: int64 */
                total_with_ua: number;
            };
            message: string;
        };
        ApiResponse_ExecuteAndSaveResponse: {
            /** Format: int32 */
            code: number;
            /** @description 执行并保存响应（安全版本，不返回密钥值） */
            data?: {
                message: string | null;
                requires_restart: boolean;
                success: boolean;
            };
            message: string;
        };
        ApiResponse_ImportResponse: {
            /** Format: int32 */
            code: number;
            /** @description 导入响应 */
            data?: {
                failed_count: number;
                failed_items: components["schemas"]["ImportFailedItem"][];
                skipped_count: number;
                success_count: number;
                total_rows: number;
            };
            message: string;
        };
        ApiResponse_LinkAnalytics: {
            /** Format: int32 */
            code: number;
            /** @description 单链接分析数据 */
            data?: {
                code: string;
                geo_distribution: components["schemas"]["GeoStats"][];
                top_referrers: components["schemas"]["ReferrerStats"][];
                /** Format: int64 */
                total_clicks: number;
                trend: components["schemas"]["TrendData"];
            };
            message: string;
        };
        ApiResponse_LinkResponse: {
            /** Format: int32 */
            code: number;
            data?: {
                click_count: number;
                code: string;
                created_at: string;
                expires_at: string | null;
                password: string | null;
                target: string;
            };
            message: string;
        };
        ApiResponse_MessageResponse: {
            /** Format: int32 */
            code: number;
            /** @description 简单消息响应 */
            data?: {
                message: string;
            };
            message: string;
        };
        ApiResponse_PostNewLink: {
            /** Format: int32 */
            code: number;
            data?: {
                code?: string | null;
                expires_at?: string | null;
                force?: boolean | null;
                password?: string | null;
                target: string;
            };
            message: string;
        };
        ApiResponse_ReloadResponse: {
            /** Format: int32 */
            code: number;
            /** @description Reload 成功响应 */
            data?: {
                /** Format: int64 */
                duration_ms: number;
                message: string;
            };
            message: string;
        };
        ApiResponse_StatsResponse: {
            /** Format: int32 */
            code: number;
            /** @description 统计信息响应 */
            data?: {
                active_links: number;
                total_clicks: number;
                total_links: number;
            };
            message: string;
        };
        ApiResponse_TrendData: {
            /** Format: int32 */
            code: number;
            /** @description 点击趋势数据 */
            data?: {
                /** @description 时间标签 */
                labels: string[];
                /** @description 点击数 */
                values: number[];
            };
            message: string;
        };
        ApiResponse_Vec_ConfigHistoryResponse: {
            /** Format: int32 */
            code: number;
            data?: {
                changed_at: string;
                changed_by: string | null;
                config_key: string;
                /** Format: int32 */
                id: number;
                new_value: string;
                old_value: string | null;
            }[];
            message: string;
        };
        ApiResponse_Vec_ConfigItemResponse: {
            /** Format: int32 */
            code: number;
            data?: {
                is_sensitive: boolean;
                key: string;
                requires_restart: boolean;
                updated_at: string;
                value: string;
                /** @description 值类型 */
                value_type: components["schemas"]["ValueType"];
            }[];
            message: string;
        };
        ApiResponse_Vec_ConfigSchema: {
            /** Format: int32 */
            code: number;
            data?: {
                action?: null | components["schemas"]["ActionType"];
                category?: string | null;
                default_value: string;
                description: string;
                editable: boolean;
                enum_options?: components["schemas"]["EnumOption"][] | null;
                key: string;
                /** @description 排序顺序（基于 Forge registry 中定义的顺序） */
                order: number;
                requires_restart: boolean;
                value_type: components["schemas"]["ValueType"];
            }[];
            message: string;
        };
        ApiResponse_Vec_GeoStats: {
            /** Format: int32 */
            code: number;
            data?: {
                city: string | null;
                /** Format: int64 */
                count: number;
                country: string;
            }[];
            message: string;
        };
        ApiResponse_Vec_ReferrerStats: {
            /** Format: int32 */
            code: number;
            data?: {
                /** Format: int64 */
                count: number;
                /** Format: double */
                percentage: number;
                referrer: string;
            }[];
            message: string;
        };
        ApiResponse_Vec_TopLink: {
            /** Format: int32 */
            code: number;
            data?: {
                /** Format: int64 */
                clicks: number;
                code: string;
            }[];
            message: string;
        };
        /** @description 认证成功响应 */
        AuthSuccessResponse: {
            /** Format: int64 */
            expires_in: number;
            message: string;
        };
        BatchCreateRequest: {
            links: components["schemas"]["PostNewLink"][];
        };
        BatchDeleteRequest: {
            codes: string[];
        };
        BatchFailedItem: {
            code: string;
            error: string;
            /** Format: int32 */
            error_code?: number | null;
        };
        BatchResponse: {
            failed: components["schemas"]["BatchFailedItem"][];
            success: string[];
        };
        BatchUpdateItem: {
            code: string;
            payload: components["schemas"]["PostNewLink"];
        };
        BatchUpdateRequest: {
            updates: components["schemas"]["BatchUpdateItem"][];
        };
        /** @description 分类统计响应 */
        CategoryStatsResponse: {
            /** Format: int64 */
            count: number;
            name: string;
            /** Format: double */
            percentage: number;
        };
        /** @description 配置 action 执行请求 */
        ConfigActionRequest: {
            action: components["schemas"]["ActionType"];
        };
        /** @description 配置 action 执行响应 */
        ConfigActionResponse: {
            value: string;
        };
        /** @description 配置历史记录响应 */
        ConfigHistoryResponse: {
            changed_at: string;
            changed_by: string | null;
            config_key: string;
            /** Format: int32 */
            id: number;
            new_value: string;
            old_value: string | null;
        };
        /** @description 配置项响应 */
        ConfigItemResponse: {
            is_sensitive: boolean;
            key: string;
            requires_restart: boolean;
            updated_at: string;
            value: string;
            /** @description 值类型 */
            value_type: components["schemas"]["ValueType"];
        };
        /** @description 配置项的 schema 元信息 */
        ConfigSchema: {
            action?: null | components["schemas"]["ActionType"];
            category?: string | null;
            default_value: string;
            description: string;
            editable: boolean;
            enum_options?: components["schemas"]["EnumOption"][] | null;
            key: string;
            /** @description 排序顺序（基于 Forge registry 中定义的顺序） */
            order: number;
            requires_restart: boolean;
            value_type: components["schemas"]["ValueType"];
        };
        /** @description 配置更新请求 */
        ConfigUpdateRequest: {
            value: string;
        };
        /** @description 配置更新响应 */
        ConfigUpdateResponse: {
            is_sensitive: boolean;
            key: string;
            message: string | null;
            requires_restart: boolean;
            value: string;
        };
        /** @description 设备分析响应 */
        DeviceAnalyticsResponse: {
            /** Format: double */
            bot_percentage: number;
            browsers: components["schemas"]["CategoryStatsResponse"][];
            devices: components["schemas"]["CategoryStatsResponse"][];
            operating_systems: components["schemas"]["CategoryStatsResponse"][];
            /** Format: int64 */
            total_with_ua: number;
        };
        /** @description 单个 enum 选项 */
        EnumOption: {
            description?: string | null;
            description_i18n_key?: string | null;
            label: string;
            label_i18n_key?: string | null;
            value: string;
        };
        /**
         * Format: int32
         * @description Shortlinker API numeric error code
         * @enum {integer}
         */
        ErrorCode: ErrorCode;
        /** @description 执行并保存响应（安全版本，不返回密钥值） */
        ExecuteAndSaveResponse: {
            message: string | null;
            requires_restart: boolean;
            success: boolean;
        };
        /** @description 导出查询参数 */
        ExportQuery: {
            created_after?: string | null;
            created_before?: string | null;
            only_active?: boolean | null;
            only_expired?: boolean | null;
            search?: string | null;
        };
        /** @description 地理位置统计 */
        GeoStats: {
            city: string | null;
            /** Format: int64 */
            count: number;
            country: string;
        };
        GetLinksQuery: {
            created_after?: string | null;
            created_before?: string | null;
            only_active?: boolean | null;
            only_expired?: boolean | null;
            page?: number | null;
            page_size?: number | null;
            search?: string | null;
        };
        /**
         * @description 分组方式
         * @enum {string}
         */
        GroupBy: "hour" | "day" | "week" | "month";
        /** @description 缓存健康检查状态 */
        HealthCacheCheck: {
            bloom_filter_enabled: boolean;
            cache_type: string;
            error?: string | null;
            negative_cache_enabled: boolean;
            status: string;
        };
        /** @description 健康检查项容器 */
        HealthChecks: {
            cache?: null | components["schemas"]["HealthCacheCheck"];
            storage: components["schemas"]["HealthStorageCheck"];
        };
        /** @description 健康检查响应 */
        HealthResponse: {
            checks: components["schemas"]["HealthChecks"];
            /** Format: int32 */
            response_time_ms: number;
            status: string;
            timestamp: string;
            /** Format: int32 */
            uptime: number;
        };
        /** @description 存储后端信息 */
        HealthStorageBackend: {
            storage_type: string;
            support_click: boolean;
        };
        /** @description 存储健康检查状态 */
        HealthStorageCheck: {
            backend: components["schemas"]["HealthStorageBackend"];
            error?: string | null;
            links_count: number | null;
            status: string;
        };
        HistoryQuery: {
            /** Format: int64 */
            limit?: number | null;
        };
        /**
         * @description HTTP 方法枚举
         * @enum {string}
         */
        HttpMethod: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS";
        /** @description 导入失败项 */
        ImportFailedItem: {
            code: string;
            error: string;
            /** Format: int32 */
            error_code?: number | null;
            /** @description CSV 行号（1-based），None 表示行号未知（如 service 层返回的冲突项无法反查行号） */
            row: number | null;
        };
        /**
         * @description Import conflict resolution mode
         * @enum {string}
         */
        ImportMode: "skip" | "overwrite" | "error";
        /** @description 导入响应 */
        ImportResponse: {
            failed_count: number;
            failed_items: components["schemas"]["ImportFailedItem"][];
            skipped_count: number;
            success_count: number;
            total_rows: number;
        };
        /** @description 单链接分析数据 */
        LinkAnalytics: {
            code: string;
            geo_distribution: components["schemas"]["GeoStats"][];
            top_referrers: components["schemas"]["ReferrerStats"][];
            /** Format: int64 */
            total_clicks: number;
            trend: components["schemas"]["TrendData"];
        };
        LinkResponse: {
            click_count: number;
            code: string;
            created_at: string;
            expires_at: string | null;
            password: string | null;
            target: string;
        };
        LoginCredentials: {
            password: string;
        };
        /** @description 简单消息响应 */
        MessageResponse: {
            message: string;
        };
        PaginatedResponse_Vec_LinkResponse: {
            /** Format: int32 */
            code: number;
            data?: {
                click_count: number;
                code: string;
                created_at: string;
                expires_at: string | null;
                password: string | null;
                target: string;
            }[];
            message: string;
            pagination: components["schemas"]["PaginationInfo"];
        };
        PaginationInfo: {
            page: number;
            page_size: number;
            total: number;
            total_pages: number;
        };
        PostNewLink: {
            code?: string | null;
            expires_at?: string | null;
            force?: boolean | null;
            password?: string | null;
            target: string;
        };
        /** @description 来源统计 */
        ReferrerStats: {
            /** Format: int64 */
            count: number;
            /** Format: double */
            percentage: number;
            referrer: string;
        };
        /** @description Reload 成功响应 */
        ReloadResponse: {
            /** Format: int64 */
            duration_ms: number;
            message: string;
        };
        /**
         * @description Cookie SameSite 策略
         * @enum {string}
         */
        SameSitePolicy: "Strict" | "Lax" | "None";
        /** @description 统计信息响应 */
        StatsResponse: {
            active_links: number;
            total_clicks: number;
            total_links: number;
        };
        /** @description 热门链接 */
        TopLink: {
            /** Format: int64 */
            clicks: number;
            code: string;
        };
        /** @description 点击趋势数据 */
        TrendData: {
            /** @description 时间标签 */
            labels: string[];
            /** @description 点击数 */
            values: number[];
        };
        /**
         * @description 配置值类型枚举
         *
         *     用于标识配置项在数据库和前端的类型。
         * @enum {string}
         */
        ValueType: "string" | "int" | "float" | "bool" | "json" | "enum" | "stringarray" | "enumarray";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_device_stats: {
        parameters: {
            query?: {
                /** @description 开始日期 (ISO 8601) */
                start_date?: string | null;
                /** @description 结束日期 (ISO 8601) */
                end_date?: string | null;
                /** @description 分组方式 */
                group_by?: null | components["schemas"]["GroupBy"];
                /** @description 返回数量限制 */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_DeviceAnalyticsResponse"];
                };
            };
        };
    };
    export_analytics_report: {
        parameters: {
            query?: {
                /** @description 开始日期 (ISO 8601) */
                start_date?: string | null;
                /** @description 结束日期 (ISO 8601) */
                end_date?: string | null;
                /** @description 分组方式 */
                group_by?: null | components["schemas"]["GroupBy"];
                /** @description 返回数量限制 */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analytics CSV report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
        };
    };
    get_geo_stats: {
        parameters: {
            query?: {
                /** @description 开始日期 (ISO 8601) */
                start_date?: string | null;
                /** @description 结束日期 (ISO 8601) */
                end_date?: string | null;
                /** @description 分组方式 */
                group_by?: null | components["schemas"]["GroupBy"];
                /** @description 返回数量限制 */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Geographic statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_GeoStats"];
                };
            };
        };
    };
    get_referrer_stats: {
        parameters: {
            query?: {
                /** @description 开始日期 (ISO 8601) */
                start_date?: string | null;
                /** @description 结束日期 (ISO 8601) */
                end_date?: string | null;
                /** @description 分组方式 */
                group_by?: null | components["schemas"]["GroupBy"];
                /** @description 返回数量限制 */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Referrer statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_ReferrerStats"];
                };
            };
        };
    };
    get_top_links: {
        parameters: {
            query?: {
                /** @description 开始日期 (ISO 8601) */
                start_date?: string | null;
                /** @description 结束日期 (ISO 8601) */
                end_date?: string | null;
                /** @description 分组方式 */
                group_by?: null | components["schemas"]["GroupBy"];
                /** @description 返回数量限制 */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Top links */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_TopLink"];
                };
            };
        };
    };
    get_analytics_trends: {
        parameters: {
            query?: {
                /** @description 开始日期 (ISO 8601) */
                start_date?: string | null;
                /** @description 结束日期 (ISO 8601) */
                end_date?: string | null;
                /** @description 分组方式 */
                group_by?: null | components["schemas"]["GroupBy"];
                /** @description 返回数量限制 */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Click trend */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_TrendData"];
                };
            };
        };
    };
    admin_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginCredentials"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AuthSuccessResponse"];
                };
            };
            /** @description Invalid administrator token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Login rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    admin_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_MessageResponse"];
                };
            };
        };
    };
    refresh_admin_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_AuthSuccessResponse"];
                };
            };
            /** @description Refresh token is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Refresh rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_admin_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token is valid */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_MessageResponse"];
                };
            };
            /** @description Token is missing or invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_configs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_ConfigItemResponse"];
                };
            };
        };
    };
    reload_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration reloaded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ReloadResponse"];
                };
            };
            /** @description Configuration reload failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_config_schema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_ConfigSchema"];
                };
            };
        };
    };
    get_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Configuration key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ConfigItemResponse"];
                };
            };
            /** @description Configuration key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Configuration key */
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdateRequest"];
            };
        };
        responses: {
            /** @description Configuration updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ConfigUpdateResponse"];
                };
            };
            /** @description Invalid configuration value */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Configuration key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    execute_config_action: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Configuration key */
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigActionRequest"];
            };
        };
        responses: {
            /** @description Action result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ConfigActionResponse"];
                };
            };
            /** @description Unsupported action */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    execute_and_save_config_action: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Configuration key */
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigActionRequest"];
            };
        };
        responses: {
            /** @description Action executed and value saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ExecuteAndSaveResponse"];
                };
            };
            /** @description Unsupported action */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_config_history: {
        parameters: {
            query?: {
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Configuration key */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_Vec_ConfigHistoryResponse"];
                };
            };
        };
    };
    list_links: {
        parameters: {
            query?: {
                page?: number | null;
                page_size?: number | null;
                created_after?: string | null;
                created_before?: string | null;
                only_expired?: boolean | null;
                only_active?: boolean | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated short links */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_Vec_LinkResponse"];
                };
            };
            /** @description Invalid filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_link: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostNewLink"];
            };
        };
        responses: {
            /** @description Short link created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PostNewLink"];
                };
            };
            /** @description Invalid short link */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Short code already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    batch_update_links: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchUpdateRequest"];
            };
        };
        responses: {
            /** @description Batch update result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_BatchResponse"];
                };
            };
            /** @description Batch too large or invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    batch_create_links: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCreateRequest"];
            };
        };
        responses: {
            /** @description Batch create result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_BatchResponse"];
                };
            };
            /** @description Batch too large or invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    batch_delete_links: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchDeleteRequest"];
            };
        };
        responses: {
            /** @description Batch delete result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_BatchResponse"];
                };
            };
            /** @description Batch too large or invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    export_links: {
        parameters: {
            query?: {
                search?: string | null;
                created_after?: string | null;
                created_before?: string | null;
                only_expired?: boolean | null;
                only_active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Short links CSV export */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            /** @description Invalid export filter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    import_links: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": unknown;
            };
        };
        responses: {
            /** @description Import result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_ImportResponse"];
                };
            };
            /** @description Invalid CSV or multipart request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Short code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Short link */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_LinkResponse"];
                };
            };
            /** @description Short link not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Short code */
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostNewLink"];
            };
        };
        responses: {
            /** @description Short link updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_PostNewLink"];
                };
            };
            /** @description Short link not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_link: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Short code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Short link deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_MessageResponse"];
                };
            };
            /** @description Short link not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_link_analytics: {
        parameters: {
            query?: {
                /** @description 开始日期 (ISO 8601) */
                start_date?: string | null;
                /** @description 结束日期 (ISO 8601) */
                end_date?: string | null;
                /** @description 分组方式 */
                group_by?: null | components["schemas"]["GroupBy"];
                /** @description 返回数量限制 */
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Short code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link analytics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_LinkAnalytics"];
                };
            };
            /** @description Short link not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_link_device_stats: {
        parameters: {
            query?: {
                /** @description 开始日期 (ISO 8601) */
                start_date?: string | null;
                /** @description 结束日期 (ISO 8601) */
                end_date?: string | null;
                /** @description 分组方式 */
                group_by?: null | components["schemas"]["GroupBy"];
                /** @description 返回数量限制 */
                limit?: number | null;
            };
            header?: never;
            path: {
                /** @description Short code */
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link device statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_DeviceAnalyticsResponse"];
                };
            };
            /** @description Short link not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_link_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Link statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse_StatsResponse"];
                };
            };
        };
    };
}
export enum ErrorCode {
    Success = 0,
    BadRequest = 1000,
    Unauthorized = 1001,
    NotFound = 1004,
    InternalServerError = 1005,
    BatchSizeTooLarge = 1010,
    FileTooLarge = 1011,
    InvalidDateFormat = 1012,
    ServiceUnavailable = 1030,
    AuthFailed = 2000,
    TokenExpired = 2001,
    TokenInvalid = 2002,
    CsrfInvalid = 2003,
    RateLimitExceeded = 2004,
    LinkNotFound = 3000,
    LinkAlreadyExists = 3001,
    LinkInvalidUrl = 3002,
    LinkInvalidExpireTime = 3003,
    LinkPasswordHashError = 3004,
    LinkDatabaseError = 3005,
    LinkEmptyCode = 3006,
    LinkInvalidCode = 3007,
    LinkReservedCode = 3008,
    ImportFailed = 4000,
    ExportFailed = 4001,
    InvalidMultipartData = 4002,
    FileReadError = 4003,
    CsvFileMissing = 4004,
    CsvParseError = 4005,
    CsvGenerationError = 4006,
    ConfigNotFound = 5000,
    ConfigUpdateFailed = 5001,
    ConfigReloadFailed = 5002,
    AnalyticsQueryFailed = 6000,
    AnalyticsLinkNotFound = 6001,
    AnalyticsInvalidDateRange = 6002
}
