//! Shortlinker OpenAPI 文档装配。

use utoipa::OpenApi;

/// 管理 API 和管理面板共享的唯一 schema 来源。
#[derive(OpenApi)]
#[openapi(
    info(
        title = "Shortlinker API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Shortlinker management API",
        license(name = "MIT"),
    ),
    paths(
        crate::api::services::admin::auth::check_admin_token,
        crate::api::services::admin::auth::refresh_token,
        crate::api::services::admin::auth::logout,
        crate::api::services::admin::auth::verify_token,
        crate::api::services::admin::link_crud::get_all_links,
        crate::api::services::admin::link_crud::post_link,
        crate::api::services::admin::link_crud::get_link,
        crate::api::services::admin::link_crud::update_link,
        crate::api::services::admin::link_crud::delete_link,
        crate::api::services::admin::link_crud::get_stats,
        crate::api::services::admin::batch_ops::batch_create_links,
        crate::api::services::admin::batch_ops::batch_update_links,
        crate::api::services::admin::batch_ops::batch_delete_links,
        crate::api::services::admin::export_import::export_links,
        crate::api::services::admin::export_import::import_links,
        crate::api::services::admin::analytics::get_trends,
        crate::api::services::admin::analytics::get_top_links,
        crate::api::services::admin::analytics::get_referrers,
        crate::api::services::admin::analytics::get_geo_stats,
        crate::api::services::admin::analytics::get_link_analytics,
        crate::api::services::admin::analytics::get_link_device_stats,
        crate::api::services::admin::analytics::get_device_stats,
        crate::api::services::admin::analytics::export_report,
        crate::api::services::admin::config_ops::get_all_configs,
        crate::api::services::admin::config_ops::get_config,
        crate::api::services::admin::config_ops::update_config,
        crate::api::services::admin::config_ops::get_config_history,
        crate::api::services::admin::config_ops::reload_config,
        crate::api::services::admin::config_ops::get_config_schema,
        crate::api::services::admin::config_ops::execute_config_action,
        crate::api::services::admin::config_ops::execute_and_save_config_action,
    ),
    components(
        schemas(
            crate::api::services::admin::error_code::ErrorCode,
            crate::api::services::admin::types::LoginCredentials,
            crate::api::services::admin::types::PostNewLink,
            crate::api::services::admin::types::GetLinksQuery,
            crate::api::services::admin::types::PaginationInfo,
            crate::api::services::admin::types::BatchCreateRequest,
            crate::api::services::admin::types::BatchUpdateRequest,
            crate::api::services::admin::types::BatchUpdateItem,
            crate::api::services::admin::types::BatchDeleteRequest,
            crate::api::services::admin::types::BatchResponse,
            crate::api::services::admin::types::BatchFailedItem,
            crate::api::services::admin::types::LinkResponse,
            crate::api::services::admin::types::StatsResponse,
            crate::api::services::admin::types::MessageResponse,
            crate::api::services::admin::types::AuthSuccessResponse,
            crate::api::services::admin::types::ReloadResponse,
            crate::api::services::admin::types::HealthStorageBackend,
            crate::api::services::admin::types::HealthStorageCheck,
            crate::api::services::admin::types::HealthChecks,
            crate::api::services::admin::types::HealthCacheCheck,
            crate::api::services::admin::types::HealthResponse,
            crate::api::services::admin::types::ExportQuery,
            crate::api::services::admin::types::ImportFailedItem,
            crate::api::services::admin::types::ImportResponse,
            crate::api::services::admin::analytics::AnalyticsQuery,
            crate::api::services::admin::analytics::GroupBy,
            crate::api::services::admin::analytics::TrendData,
            crate::api::services::admin::analytics::TopLink,
            crate::api::services::admin::analytics::ReferrerStats,
            crate::api::services::admin::analytics::GeoStats,
            crate::api::services::admin::analytics::LinkAnalytics,
            crate::api::services::admin::analytics::DeviceAnalyticsResponse,
            crate::api::services::admin::analytics::CategoryStatsResponse,
            crate::api::services::admin::config_ops::ConfigItemResponse,
            crate::api::services::admin::config_ops::ConfigUpdateRequest,
            crate::api::services::admin::config_ops::ConfigUpdateResponse,
            crate::api::services::admin::config_ops::ConfigHistoryResponse,
            crate::api::services::admin::config_ops::ConfigActionRequest,
            crate::api::services::admin::config_ops::ConfigActionResponse,
            crate::api::services::admin::config_ops::ExecuteAndSaveResponse,
            crate::api::services::admin::config_ops::HistoryQuery,
            crate::config::types::ActionType,
            crate::config::ValueType,
            crate::config::ConfigSchema,
            crate::config::EnumOption,
            crate::config::SameSitePolicy,
            crate::config::HttpMethod,
            crate::services::ImportMode,
        )
    ),
    tags(
        (name = "links", description = "Short link management"),
        (name = "analytics", description = "Click analytics"),
        (name = "auth", description = "Administrator authentication"),
        (name = "config", description = "Runtime configuration"),
        (name = "health", description = "Service health"),
    ),
)]
pub struct ApiDoc;
